// MIT License
//
// Copyright (c) 2022 Daniele Sluijters
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// WARNING: This file is generated by ssrfgen. DO NOT EDIT.

package ssrf

import (
	"net/netip"
)

var (
	// IPv4SpecialPurpose contains IPv4 special purpose IP prefixes
	// https://www.iana.org/assignments/iana-ipv4-special-registry/iana-ipv4-special-registry.xhtml
	IPv4SpecialPurpose = []netip.Prefix{
		netip.MustParsePrefix("0.0.0.0/8"),       // "This network" (RFC 791, Section 3.2)
		netip.MustParsePrefix("10.0.0.0/8"),      // Private-Use (RFC 1918)
		netip.MustParsePrefix("100.64.0.0/10"),   // Shared Address Space (RFC 6598)
		netip.MustParsePrefix("127.0.0.0/8"),     // Loopback (RFC 1122, Section 3.2.1.3)
		netip.MustParsePrefix("169.254.0.0/16"),  // Link Local (RFC 3927)
		netip.MustParsePrefix("172.16.0.0/12"),   // Private-Use (RFC 1918)
		netip.MustParsePrefix("192.0.0.0/24"),    // IETF Protocol Assignments (RFC 6890, Section 2.1)
		netip.MustParsePrefix("192.0.2.0/24"),    // Documentation (TEST-NET-1) (RFC 5737)
		netip.MustParsePrefix("192.31.196.0/24"), // AS112-v4 (RFC 7535)
		netip.MustParsePrefix("192.52.193.0/24"), // AMT (RFC 7450)
		netip.MustParsePrefix("192.88.99.0/24"),  // Deprecated (6to4 Relay Anycast) (RFC 7526)
		netip.MustParsePrefix("192.168.0.0/16"),  // Private-Use (RFC 1918)
		netip.MustParsePrefix("192.175.48.0/24"), // Direct Delegation AS112 Service (RFC 7534)
		netip.MustParsePrefix("198.18.0.0/15"),   // Benchmarking (RFC 2544)
		netip.MustParsePrefix("198.51.100.0/24"), // Documentation (TEST-NET-2) (RFC 5737)
		netip.MustParsePrefix("203.0.113.0/24"),  // Documentation (TEST-NET-3) (RFC 5737)
		netip.MustParsePrefix("240.0.0.0/4"),     // Reserved (RFC 1112, Section 4)
		netip.MustParsePrefix("224.0.0.0/4"),     // Multicast (RFC 1112, Section 4)
	}

	// IPv6SpecialPurpose contains IPv6 special purpose IP prefixes
	// https://www.iana.org/assignments/iana-ipv6-special-registry/iana-ipv6-special-registry.xhtml
	IPv6SpecialPurpose = []netip.Prefix{
		netip.MustParsePrefix("::1/128"),           // Loopback Address (RFC 4291)
		netip.MustParsePrefix("::/128"),            // Unspecified Address (RFC 4291)
		netip.MustParsePrefix("::ffff:0:0/96"),     // IPv4-mapped Address (RFC 4291)
		netip.MustParsePrefix("64:ff9b::/96"),      // IPv4-IPv6 Translation (RFC 6052)
		netip.MustParsePrefix("64:ff9b:1::/48"),    // IPv4-IPv6 Translation (RFC 8215)
		netip.MustParsePrefix("100::/64"),          // Discard-Only Address Block (RFC 6666)
		netip.MustParsePrefix("2001::/23"),         // IETF Protocol Assignments (RFC 2928)
		netip.MustParsePrefix("2001:db8::/32"),     // Documentation (RFC 3849)
		netip.MustParsePrefix("2002::/16"),         // 6to4 (RFC 3056)
		netip.MustParsePrefix("2620:4f:8000::/48"), // Direct Delegation AS112 Service (RFC 7534)
		netip.MustParsePrefix("fc00::/7"),          // Unique-Local (RFC 4193, RFC 8190)
		netip.MustParsePrefix("fe80::/10"),         // Link-Local Unicast (RFC 4291)
		netip.MustParsePrefix("fec0::/10"),         // Deprecated (site-local) (RFC 3879)
		netip.MustParsePrefix("ff00::/8"),          // Multicast (RFC 4291)
	}
)
