name: Skip on ignored paths
on:
  pull_request:
    paths-ignore:
      - '**.go'
      - '.github/workflows/test.yaml'
    branches:
      - main
  push:
    paths-ignore:
      - '**.go'
      - '.github/workflows/test.yaml'
    branches:
      - main
    tags-ignore:
      - '**'

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.19.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - run: 'echo "No build required" '
